[MeasureParent]
Measure=Plugin
Plugin=WebNowPlaying

[MEASUREPARENT]
Measure=Plugin
Plugin=WebNowPlaying



[MeasureParent]
Measure=Plugin
Plugin=WebNowPlaying



[MeasureParent]
Measure=Plugin
Plugin=WebNowPlaying



[MeasureParent]
Measure=Plugin
Plugin=WebNowPlaying



[MeasureParent]

[]
Measure=Plugin
Plugin=WebNowPlaying



[MeasureParent]
Measure=Plugin
Plugin=WebNowPlaying



[MeasureCover]
PlayerType=Cover
Res=300
DefaultPath=#@#Default.png
Measure=Plugin
Plugin=WebNowPlaying

[MeasureProgress]
PlayerType=Progress
Measure=Plugin
Plugin=WebNowPlaying

[MeterCover]
 Meter=Image
 ImageName=[MeasureCover]
 LeftMouseUpAction=[!CommandMeasure "MeasureProgress" "PlayPause"]
 X=0
 Y=0
 W=300
 H=300
 DynamicVariables=1










































